version: '3.9'
services:
  nextjs:
    restart: always
    image: alkuinvito/electrobuzz:latest
    env_file: .env
    expose:
      - 3000
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}