name: deploy

on:
  push:
    branches:
      - "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: alkuinvito/electrobuzz:latest
          secrets: "prisma_key=${{ secrets.PRISMA_FIELD_ENCRYPTION_KEY }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Spin up docker image
        uses: appleboy/ssh-action@v0.1.10
        env:
          TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: CF_TUNNEL_TOKEN
          script: |
            cd ~/deploy
            docker pull alkuinvito/electrobuzz:latest
            docker compose up -d --force-recreate